In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr.shape)
# outupt: (4,)

# reshaping the arr
"""
arr.reshape(3,3)
print(arr)
this code will trow the error:
The general rule for reshaping the array is 
arr.reshape(x,y)
x * y == len(array)
the new row and column product is equal to total element of array
arr  have 4 element but we try to reshape(3,3) where 3 * 3 is 9
so it doesn't match it will throw the error
"""
new_arr = arr.reshape(4,1)
print(new_arr)


(4,)
[[1]
 [2]
 [3]
 [4]]


In [ ]:
# creating 2D array and reshaping it

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

# reshaping the arr2
new_arr = arr2.reshape(3,2)
print(f"New array:{new_arr}")
print(new_arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
New array:[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
# another method to create the array and attributes of nupmy
arr = np.arange(6).reshape(3,2)
print(f"Array:{arr}")
print(f"Dimension:{arr.ndim}")
print(f"Length:{len(arr)}")
print(f"Shape:{arr.shape}")
print(f"Array datatype:{arr.dtype}")
print(f"Number of elements in array:{arr.size}")
print(f"Item size (in bytes):{arr.itemsize}")


Array:[[0 1]
 [2 3]
 [4 5]]
Dimension:2
Length:3
Shape:(3, 2)
Array datatype:int64
Number of elements in array:6
Item size (in bytes):8


In [ ]:
# Vectorized Operations : operate with each element 
arr1 = np.arange(9).reshape(3,3)
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

# addition 
print(f"Addition:\n{arr1 + arr2}")
# subtraction 
print(f"Subtraction:\n{arr1 - arr2}")
# Division 
print(f"Division:\n{arr1 / arr2}")
# Multiplication 
print(f"Multiplication:\n{arr1 * arr2}")

Addition:
[[10 12 14]
 [16 18 20]
 [22 24 26]]
Subtraction:
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
Division:
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]
Multiplication:
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [ ]:
# Universal Functions  NumPy provides universal functions (ufuncs) that operate element-wise on arrays, such as sqrt, exp, sin, and log.

arr = np.array([16,36,49,64,16])

# square root
print(f"Square root:{np.sqrt(arr)}")

# exponential
print(f"Exponential:\n{np.exp(arr)}")


Square root:[4.         6.         7.         8.         9.48683298]
Exponential:
[8.88611052e+06 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.22040329e+39]
Sin:
[-0.28790332 -0.99177885 -0.95375265  0.92002604  0.89399666]


In [48]:
# Accessing and slicing array

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# slicing 3x4 matrix
# slice and get the 1,2,5,6
print(f"Sliced:{arr2[:2,:2]}")

# modifing
arr2[:3,:] = 50 #it will replace the all the value with 50
print(f"Modified:\n{arr2}") 

[2 3 4]
Sliced:[[1 2]
 [5 6]]
Modified:
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


In [ ]:
# matrixes using numpy array
# 2x2 matrix of 0
n_zeros = np.zeros((2,2))
print(f"{n_zeros}") 

# 2x2 matrix of 1
n_ones = np.ones((2,2))
print(f"{n_ones}")

# identity matrix
iden_matrix = np.eye(3,3)
print(f"Identity matrix:\n{iden_matrix}")

# diagonal matrix:
dia_matrix = np.diag([1,2,3])
print(f"Diangonal matrix:\n{dia_matrix}")

# upper triangular and lower triangular 
uptri = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Upper triangular:\n{uptri}")

lowtri = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Lower triangular:\n{lowtri}")

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diangonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Upper triangular:
[[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower triangular:
[[1 0 0]
 [4 5 0]
 [7 8 9]]
